### ISSUE TITLE
Test Extraction on SIRT1 Publication (Has Many Interactions)

### ISSUE THREAD

**Issue by cannin** [ndexbio/gsoc_llm#2]
This review is a good test case because it has many interactions ~ 90 interactions

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3898398/

The "Additional file 2" (at bottom) has the interactions included in the publication. Work to retrieve as many as possible and report how many you are retrieving. I expect you try to get at least ~70 interactions before reporting.

**Comment by Favourj-bit** [comment]
Another document to try out that came up during the kickoff meeting

https://pubmed.ncbi.nlm.nih.gov/28404643/

**Comment by cannin** [comment]
@Favourj-bit That article happened to be in the examples; this is not an important for this project. If you are in need more articles, use the ones in the zip file (PMIDs provided); this is related to #7 

[indra_adrenocortical_carcinoma_v2.zip](https://github.com/ndexbio/gsoc_llm/files/15277179/indra_adrenocortical_carcinoma_v2.zip)

> Another document to try out that came up during the kickoff meeting
> 
> https://pubmed.ncbi.nlm.nih.gov/28404643/

**Comment by Favourj-bit** [comment]
@cannin Alright, noted. Thank you

**Comment by Favourj-bit** [comment]
Hello @cannin, so i tested out langchain on the paper and I was able to parse through the whole document. There is just something i need clarity on. I tried to get the number of interactions and number of unique interactions, I don't know if I should be getting unique interactions since all interactions are supposed to be a different one
<img width="825" alt="Screenshot 2024-05-13 at 19 10 42" src="https://github.com/ndexbio/gsoc_llm/assets/63251266/79eb190f-c852-416e-8f34-2da4885a91dd">

The first result is what I got without specifying anything about uniqueness and it reports 158 interactions
The other one is what I got when I tried to specify uniqueness.

I have attached the json files that shows the different outputs here: https://github.com/ndexbio/gsoc_llm/tree/094a972ab9bb84009db73b1cc84721fc6337a6ff/results/SIRT1_PARP1

**Comment by cannin** [comment]
@Favourj-bit as discussed the review article is very dense with interactions; try working with PMC6044858 first

**Comment by Favourj-bit** [comment]
@cannin , I have been able to test the other paper you suggested using gpt. However, I am having issues with coming up with code to compare the both because they seem to be represented a little differently. I don't know if you might have any suggestion for me to write a comparison code. I have attached some screenshots that shows what i am talking about
<img width="459" alt="Screenshot 2024-05-18 at 04 17 39" src="https://github.com/ndexbio/gsoc_llm/assets/63251266/0f39b11f-af41-44fe-a190-17414d715d4e">

<img width="971" alt="Screenshot 2024-05-18 at 04 05 50" src="https://github.com/ndexbio/gsoc_llm/assets/63251266/65f5679e-32e6-4c47-85e5-324be8aaa721">
<img width="974" alt="Screenshot 2024-05-18 at 04 06 03" src="https://github.com/ndexbio/gsoc_llm/assets/63251266/6f93d989-fd8e-48e7-94bc-c02998091736">

**Comment by cannin** [comment]
No easy fix for you, but that's why I said use/make a format compatible with both NDEX and INDRA (see #7). Remember, important to know what matches or not; not just an overall X INDRA and Y GPT counts.

**Comment by Favourj-bit** [comment]
@cannin 
I have been able to extract interactions from this document based on sentences. I noticed that the extraction chain does not still extract the sentence as the interaction details upon directly specifying it in the prompt and in the schematic. This is the result from the code:
https://github.com/ndexbio/gsoc_llm/blob/main/results/pmc6044858/sentence_output.json

**Comment by cannin** [comment]
Don't trust or ask GPT to get the sentence. Get the result, if it is JSON, then dump it into a dictionary variable in Python and add the sentence.
